website/Music/urls.py
from django.urls import path
from django.urls import re_path
from . import views

app_name= 'music'
urlpatterns = [
    re_path('^$', views.index, name ='index'),
    re_path('^(?P<album_id>[0-9]+)/$', views.details,name='detail'),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('Music.urls')),

]

website/Music/models.py
from django.db import models

# Create your models here.
class Artist (models.Model):
    artist_name = models.CharField(max_length=100)
    def __str__(self):
        return self.artist_name

class Genre(models.Model):
    genre_title = models.CharField(max_length=50)
    def __str__(self):
        return self.genre_title

class Album (models.Model):
    releasedate = models.DateTimeField()
    album_title = models.CharField(max_length=250)
    album_logo = models.CharField(max_length=1000)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    genre = models.ForeignKey(Genre,on_delete=models.CASCADE)
    studio = models.CharField(max_length=100)
    def __str__(self):
        return self.album_title
class Song (models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type= models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    def __str__(self):
        return self.song_title


website/Music/views.py
from .models import Genre,Album,Song
from django.shortcuts import render, get_object_or_404
# Create your views here.
def index(request) :
    all_albums=Album.objects.all()
    all_songs=Song.objects.all()
    context = {'all_albums':all_albums}

    return render(request, 'music/index.html',context)
    # html = ''
    # for album in all_albums:
    #     url='/music/'+ str(album.id)
    #     html += '<a href="' + url + '">' + str(album.genre_title) +'</a><br>'
def details(request, album_id):
    album = get_object_or_404(Album,pk = album_id)
    # try:
    #     album = Album.objects.get(pk=album_id)
    # except Album.DoesNotExist:
    #     raise  Http404("There no such album :((")
    return render(request,'music/detail.html',{'album':album})

website/Music/templates/music/detail.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
<link rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!--Logo-->
        <div class="navbar-header">
            <a class="navbar-header" href="{%  url 'music:index' %}"> <img src="{% static 'music/images/Logo.png' %}" height="60" width="85"></a>
        </div>
        <div id="container" class="container">
            <div class="header">
                <div class="fa-header"> <h2>{{   album.artist.artist_name }} -  {{   album.album_title}}</h2></div>
            </div>
        </div>
    </div>
</nav>
<img src="{{ album.album_logo }}" height="250" width="250">
{#<h2>{{   album.album_title}}</h2>#}
<h3>Список песен: </h3>

{% if album.song_set.all %}
    <ul>
        {% for song in album.song_set.all %}
        <li>{{  song.song_title }}</li>
        {% endfor %}
    </ul>
{% else %}
    <h4>There are no added songs yet :(</h4>
{% endif %}
<h5>Дата выпуска :  {{   album.releasedate }}</h5>
<h5>Студия :  {{   album.studio }} </h5>

website/Music/templates/music/index.html
<!-- Путь к CSS -->
{% load staticfiles %}
<link rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!--Logo-->
        <div class="navbar-header">
            <a class="navbar-header" href="{%  url 'music:index' %}"> <img src="{% static 'music/images/Logo.png' %}" height="60" width="85"></a>
        </div>
        <div id="container" class="container">
            <div class="header">
                <div class="fa-header"> <h2>Список альбомов</h2></div>
            </div>
        </div>
    </div>
</nav>

{% if all_albums %}
    <ul>
        {% for album in all_albums %}
           <li><img src=" {{ album.album_logo }}" height="40" width="40"> <a href="{% url 'music:detail' album.id %}">  {{ album.artist.artist_name }}  -  {{ album.album_title }}</a> </li>
        {% endfor %}
    </ul>
{% else %}
    <h3>There are no albums here</h3>
{% endif %}